nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.9.2.cjs

pnpMode: loose

pnpFallbackMode: all

packageExtensions:
  "@prisma/client@*":
    peerDependencies:
      "typescript": "*"
    dependencies:
      ".prisma": "*"
